### ISSUE TITLE
Detect color slot layouts and adjust font color for those

### ISSUE THREAD

**Issue by mathieudevos** [Eivonz/Pyfa-Mod#1]
Hey,

Super happy with the dark mode so far, however, if you have "color fitting view by slot" on, the font colors end up quite wonky. 

If that settings is on, the recommendation would be to have the everything high slot / mid slot / low slot contain a dark colored font, and others (like rigs & ammo) remain with the white font color.

Cheers

**Comment by Eivonz** [comment]
Thanks for you feedback.

You are absolutely correct, with the option "Color fitting view by slot" enabled, using a light font color is not ideal for the active fitting window. Very well spotted.

I have made a note of this issue, though currently I don't have the means to implement a partial condition based on a Pyfa setting. (I might give it a look when I have a bit more time)

**Comment by Eivonz** [comment]
@mathieudevos 

I have addressed this issue, and it should now be fixed as you suggested in release [v1.0.1](https://github.com/Eivonz/Pyfa-Mod/releases/tag/v1.0.1) :)

Cheers
