### ISSUE TITLE
Compare Module Stats is unreadable.

### ISSUE THREAD

**Issue by JoeyNieuwkoop** [Eivonz/Pyfa-Mod#2]
Hey! First of all, great that you made dark mode, Pyfa needed one :)

The Compare stats window though is unreadable because half of the lines have a bright background as well as white taext, which makes it difficult to read the texts. If you are still active on this, is it possible you could change this?

I have added what I meant in the attachment.

![Unreadable_Compare](https://github.com/Eivonz/Pyfa-Mod/assets/10940267/1c72eec0-707b-439e-8c59-87e1b997a884)

**Comment by Eivonz** [comment]
Hey

Apologies for not noticing your Issue sooner, for some reason I missed the notification email for this.
Nonetheless I intend to release a new updated build within a week or so, with a fix to the "Module comparison stats" window included.

**Comment by JoeyNieuwkoop** [comment]
Hello! 
Someone made a pull request for the repo with this fix in it, I have checked it and it fixes the module comparison window. Can look at that :)
Thanks for the response

**Comment by Eivonz** [comment]
I have released an updated build including the fix supplied in mentioned pull request.

You can fetch the latest build here: [v1.0.2](https://github.com/Eivonz/Pyfa-Mod/releases/tag/v1.0.2) and I would love if you could confirm it fixes the issue before I close this one.

**Comment by JoeyNieuwkoop** [comment]
If the fix came from the pull request then it does fix the compare window! I have checked that :)
